-- CreateTable
CREATE TABLE "Account" (
    "id" SERIAL NOT NULL,
    "accountName" TEXT NOT NULL,
    "printName" TEXT NOT NULL,
    "openingBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "drCr" TEXT NOT NULL,
    "country" TEXT,
    "countryCode" TEXT,
    "state" TEXT,
    "stateCode" TEXT,
    "district" TEXT,
    "taluka" TEXT,
    "city" TEXT,
    "area" TEXT,
    "address1" TEXT,
    "address2" TEXT,
    "pincode" TEXT,
    "phone" TEXT,
    "mobile" TEXT,
    "email" TEXT,
    "contactPerson" TEXT,
    "birthday" TIMESTAMP(3),
    "anniversary" TIMESTAMP(3),
    "bankAccountNo" TEXT,
    "bankName" TEXT,
    "ifscCode" TEXT,
    "branch" TEXT,
    "gstNo" TEXT,
    "panCard" TEXT,
    "aadharNo" TEXT,
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);
