-- CreateTable
CREATE TABLE "Lead" (
    "id" SERIAL NOT NULL,
    "modelId" INTEGER,
    "variantId" INTEGER,
    "colourId" INTEGER,
    "customerId" INTEGER,
    "executiveId" INTEGER,
    "wantsFinance" BOOLEAN NOT NULL DEFAULT false,
    "existingCustomerModel" TEXT,
    "existingCustomerVariant" TEXT,
    "existingVehicleYear" TEXT,
    "customerExpectedPrice" DOUBLE PRECISION,
    "marketPrice" DOUBLE PRECISION,
    "exchangeBonus" DOUBLE PRECISION,
    "smiplShares" DOUBLE PRECISION,
    "dealerShares" DOUBLE PRECISION,
    "valueAddAccessories" DOUBLE PRECISION,
    "insurance" DOUBLE PRECISION,
    "totalValue" DOUBLE PRECISION,
    "expectedPurchaseDate" TIMESTAMP(3),
    "expectedDeliveryDate" TIMESTAMP(3),
    "expectedDeliveryTime" TEXT,
    "purchaseType" TEXT,
    "professionId" INTEGER,
    "enquiryTypeId" INTEGER,
    "enquirySourceId" INTEGER,
    "enquiryStatusId" INTEGER,
    "bookingDate" TIMESTAMP(3),
    "followUpDate" TIMESTAMP(3),
    "dmsEnquiryNo" TEXT,
    "dmsEnquiryDate" TIMESTAMP(3),
    "otherModel" TEXT,
    "competitorTestRide" TEXT,
    "salesManagerRemarks" TEXT,
    "dealerRemarks" TEXT,
    "advancePayment" BOOLEAN NOT NULL DEFAULT false,
    "listOfBooking" DOUBLE PRECISION,
    "paymentMode" TEXT,
    "bankMode" TEXT,
    "accountId" INTEGER,
    "narration" TEXT,
    "chequeNo" TEXT,
    "chequeDate" TIMESTAMP(3),
    "chequeClearDate" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Lead_pkey" PRIMARY KEY ("id")
);
