import { Router } from "express";
import authRoutes from "./routes/auth.js";
import companyRoute from "./routes/company.js";
import categoryRoutes from "./routes/category.js";
import brandRoutes from "./routes/brand.js";
import modelRoutes from "./routes/model.js";
import modelYearRoutes from "./routes/modelYear.js";
import variantRoutes from "./routes/variant.js";
import websiteVariantRoutes from "./routes/websiteVariant.js";
import colourRoutes from "./routes/colour.js";
import accountRoutes from "./routes/account.js";
import enquiryTypeRoutes from "./routes/enquiryType.js";
import enquirySourceRoutes from "./routes/enquirySource.js";
import professionRoutes from "./routes/profession.js";
import bankerRoutes from "./routes/banker.js";
import financeRoutes from "./routes/finance.js";
import enquiryStatusRoutes from "./routes/enquiryStatus.js";
import employeeRoutes from "./routes/employee.js";
import showroomVariantRoutes from "./routes/showroomVariant.js";
import tractorRoutes from "./routes/tractor.js";
import profilePrefixRoutes from "./routes/profilePrefix.js";
import purchaseRoutes from "./routes/purchase.js";
import leadRoutes from "./routes/lead.js";
const router = Router();

router.use("/auth", authRoutes);
router.use("/company", companyRoute);
router.use("/category", categoryRoutes);
router.use("/brand", brandRoutes);
router.use("/model", modelRoutes);
router.use("/model-year", modelYearRoutes);
router.use("/variant", variantRoutes);
router.use("/website-variants", websiteVariantRoutes);
router.use("/colours", colourRoutes);
router.use("/accounts", accountRoutes);
router.use("/enquiry-types", enquiryTypeRoutes);
router.use("/enquiry-sources", enquirySourceRoutes);
router.use("/professions", professionRoutes);
router.use("/bankers", bankerRoutes);
router.use("/finances", financeRoutes);
router.use("/enquiry-statuses", enquiryStatusRoutes);
router.use("/employees", employeeRoutes);
router.use("/showroom-variant", showroomVariantRoutes);
router.use("/profile-prefix", profilePrefixRoutes);
router.use("/purchases", purchaseRoutes);
router.use("/tractors", tractorRoutes);


router.use("/leads", leadRoutes);
export default router;
