import { Router } from "express";
import authRoutes from "./routes/auth.js";
import companyRoute from "./routes/company.js";
import categoryRoutes from "./routes/category.js";
import brandRoutes from "./routes/brand.js";
import modelRoutes from "./routes/model.js";
import modelYearRoutes from "./routes/modelYear.js";
import variantRoutes from "./routes/variant.js";
import websiteVariantRoutes from "./routes/websiteVariant.js";
const router = Router();

router.use("/auth", authRoutes);
router.use("/company", companyRoute);
router.use("/category", categoryRoutes);
router.use("/brand", brandRoutes);
router.use("/model", modelRoutes);
router.use("/model-year", modelYearRoutes);
router.use("/variant", variantRoutes);
router.use("/website-variants", websiteVariantRoutes);
export default router;
