import { Router } from "express";
import authRoutes from "./routes/auth.js";
import companyRoute from "./routes/company.js";
import categoryRoutes from "./routes/category.js";
import brandRoutes from "./routes/brand.js";
import modelRoutes from "./routes/model.js";
import modelYearRoutes from "./routes/modelYear.js";
import variantRoutes from "./routes/variant.js";
import websiteVariantRoutes from "./routes/websiteVariant.js";
import colourRoutes from "./routes/colour.js";
import accountRoutes from "./routes/account.js";
import enquiryTypeRoutes from "./routes/enquiryType.js";
import enquirySourceRoutes from "./routes/enquirySource.js";
import professionRoutes from "./routes/profession.js";
import bankerRoutes from "./routes/banker.js";
import financeRoutes from "./routes/finance.js";
import enquiryStatusRoutes from "./routes/enquiryStatus.js";
import employeeRoutes from "./routes/employee.js";
import showroomVariantRoutes from "./routes/showroomVariant.js";
import tractorRoutes from "./routes/tractor.js";
import profilePrefixRoutes from "./routes/profilePrefix.js";
import purchaseRoutes from "./routes/purchase.js";
import leadRoutes from "./routes/lead.js";
import followupRoutes from "./routes/followup.js";
import accessoryRoutes from "./routes/accessories.js";
import accessoriesPurchaseRoutes from "./routes/accessoriesPurchase.js";
import cashPaymentRoutes from "./routes/cashPayment.js";
import bankPaymentRoutes from "./routes/bankPayment.js";
import ledgerRoutes from "./routes/ledger.js";
import contraRoutes from "./routes/contra.js";
import cashReceiptRoutes from "./routes/cashReceipt.js";
import bankReceiptRoutes from "./routes/bankReceipt.js";
import branchRoutes from "./routes/branch.js";
import vehicleStockTransferRoutes from "./routes/vehicleStockTransfer.js";
import orderRoutes from "./routes/order.js";
import webauthRoutes from "./routes/webauth.js";
import vendorRoutes from "./routes/vendor.js";
import salesExecutiveRoutes from "./routes/employee/salesexecutive/index.js";
import WebvendorRoutes from "./routes/vendor/index.js";
import testDriveRoutes from "./routes/testDrive.js";
import compareTractorRoutes from "./routes/compareTractor.js"
import accountantRoute from "./routes/employee/accountant/index.js"
import wishlistRoutes from "./routes/wishlist.js";
import notificationRoutes from "./routes/notification.js";
import storemanagerRoutes from "./routes/employee/storemanger/index.js"
const router = Router();

router.use("/auth", authRoutes);
router.use("/company", companyRoute);
router.use("/category", categoryRoutes);
router.use("/brand", brandRoutes);
router.use("/model", modelRoutes);
router.use("/model-year", modelYearRoutes);
router.use("/variant", variantRoutes);
router.use("/website-variants", websiteVariantRoutes);
router.use("/colours", colourRoutes);
router.use("/accounts", accountRoutes);
router.use("/enquiry-types", enquiryTypeRoutes);
router.use("/enquiry-sources", enquirySourceRoutes);
router.use("/professions", professionRoutes);
router.use("/bankers", bankerRoutes);
router.use("/finances", financeRoutes);
router.use("/enquiry-statuses", enquiryStatusRoutes);
router.use("/employees", employeeRoutes);
router.use("/showroom-variant", showroomVariantRoutes);
router.use("/profile-prefix", profilePrefixRoutes);
router.use("/purchases", purchaseRoutes);
router.use("/tractors", tractorRoutes);
router.use("/leads", leadRoutes);
router.use("/followup", followupRoutes);
router.use("/accessories", accessoryRoutes);
router.use("/accessories-purchase", accessoriesPurchaseRoutes);
router.use("/cash-payment", cashPaymentRoutes);
router.use("/bank-payment", bankPaymentRoutes);
router.use("/ledger", ledgerRoutes);
router.use("/contra", contraRoutes);
router.use("/cash-receipt", cashReceiptRoutes);
router.use("/bank-receipt", bankReceiptRoutes);
router.use("/branch", branchRoutes);
router.use("/vehicle-stock-transfer", vehicleStockTransferRoutes);
router.use("/orders", orderRoutes);
router.use("/webauth", webauthRoutes);
router.use("/vendor", vendorRoutes);
router.use("/salesexecutive", salesExecutiveRoutes);
router.use("/vendor-web", WebvendorRoutes);
router.use("/test-drives", testDriveRoutes);
router.use("/compare-tractor", compareTractorRoutes);
router.use("/accountant", accountantRoute);
router.use("/storemanager", storemanagerRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/notifications", notificationRoutes);
export default router;
