-- CreateTable
CREATE TABLE "WebsiteVariant" (
    "id" SERIAL NOT NULL,
    "currentStep" INTEGER NOT NULL DEFAULT 1,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "isCompleted" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "categoryId" INTEGER,
    "brandId" INTEGER,
    "modelId" INTEGER,
    "modelYearId" INTEGER,
    "variantId" INTEGER,
    "variantCode" TEXT,
    "productCode" TEXT,
    "skuCode" TEXT,
    "launchYear" INTEGER,
    "country" TEXT,
    "tractorStatus" TEXT,
    "shortDescription" TEXT,
    "highlight1" TEXT,
    "highlight2" TEXT,
    "highlight3" TEXT,
    "highlight4" TEXT,
    "highlight5" TEXT,
    "redColor" BOOLEAN NOT NULL DEFAULT false,
    "blueColor" BOOLEAN NOT NULL DEFAULT false,
    "greenColor" BOOLEAN NOT NULL DEFAULT false,
    "orangeColor" BOOLEAN NOT NULL DEFAULT false,
    "blackColor" BOOLEAN NOT NULL DEFAULT false,
    "whiteColor" BOOLEAN NOT NULL DEFAULT false,
    "customColor" BOOLEAN NOT NULL DEFAULT false,
    "customColorName" TEXT,
    "customColorCode" TEXT,
    "availableStates" JSONB,
    "availableDistricts" JSONB,
    "availableDealers" JSONB,
    "stockStatus" TEXT,
    "seoTitle" TEXT,
    "seoUrl" TEXT,
    "metaDescription" TEXT,
    "keywords" TEXT,
    "engineType" TEXT,
    "fuelType" TEXT,
    "horsePower" INTEGER,
    "numberOfCylinders" TEXT,
    "cubicCapacity" INTEGER,
    "ratedRpm" INTEGER,
    "aspiratedType" TEXT,
    "emissionNorms" TEXT,
    "coolingSystem" TEXT,
    "airFilterType" TEXT,
    "maximumTorque" DOUBLE PRECISION,
    "torqueRpm" DOUBLE PRECISION,
    "torqueBackup" DOUBLE PRECISION,
    "engineCondition" TEXT,
    "clutchType" TEXT,
    "forwardGears" INTEGER,
    "reverseGears" INTEGER,
    "gearType" TEXT,
    "transmissionType" TEXT,
    "ptoHp" INTEGER,
    "ptoRpm" INTEGER,
    "ptoType" TEXT,
    "ptoPosition" TEXT,
    "creeperGears" BOOLEAN NOT NULL DEFAULT false,
    "shuttleShift" BOOLEAN NOT NULL DEFAULT false,
    "sideShiftGear" BOOLEAN NOT NULL DEFAULT false,
    "powerShuttle" BOOLEAN NOT NULL DEFAULT false,
    "hiLoGears" BOOLEAN NOT NULL DEFAULT false,
    "multiSpeedPto" BOOLEAN NOT NULL DEFAULT false,
    "reversePto" BOOLEAN NOT NULL DEFAULT false,
    "superReducer" BOOLEAN NOT NULL DEFAULT false,
    "liftingCapacity" INTEGER,
    "liftingCapacityAt610mm" INTEGER,
    "hydraulicType" TEXT,
    "addc" BOOLEAN NOT NULL DEFAULT false,
    "positionControl" BOOLEAN NOT NULL DEFAULT false,
    "draftControl" BOOLEAN NOT NULL DEFAULT false,
    "controlType" TEXT,
    "remoteValveType" TEXT,
    "numberOfRemoteValves" TEXT,
    "threePointLinkage" TEXT,
    "linkageCategory" TEXT,
    "topLink" TEXT,
    "draftSensitivity" TEXT,
    "externalHydraulicCylinder" BOOLEAN NOT NULL DEFAULT false,
    "selfLevelling" BOOLEAN NOT NULL DEFAULT false,
    "quickHitch" BOOLEAN NOT NULL DEFAULT false,
    "downPositionControl" BOOLEAN NOT NULL DEFAULT false,
    "loadSensing" BOOLEAN NOT NULL DEFAULT false,
    "flowControl" BOOLEAN NOT NULL DEFAULT false,
    "returnToDepth" BOOLEAN NOT NULL DEFAULT false,
    "transportLock" BOOLEAN NOT NULL DEFAULT false,
    "exShowroomPrice" DOUBLE PRECISION,
    "onRoadPrice" DOUBLE PRECISION,
    "currency" TEXT,
    "gst" DOUBLE PRECISION,
    "tcsApplicable" TEXT,
    "tcsPercentage" DOUBLE PRECISION,
    "financeAvailable" TEXT,
    "emiAvailable" TEXT,
    "downPayment" DOUBLE PRECISION,
    "offerPrice" DOUBLE PRECISION,
    "negotiable" TEXT,
    "exchangeOffer" TEXT,
    "state" TEXT,
    "district" TEXT,
    "taluka" TEXT,
    "city" TEXT,
    "pincode" TEXT,
    "landmark" TEXT,
    "fullAddress" TEXT,
    "searchLocation" TEXT,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "frontView" TEXT,
    "leftView" TEXT,
    "rightView" TEXT,
    "rearView" TEXT,
    "engineView" TEXT,
    "dashboardView" TEXT,
    "tyreView" TEXT,
    "hydraulicView" TEXT,
    "ptoView" TEXT,
    "chassisNumber" TEXT,
    "rcBook" TEXT,
    "additionalImage1" TEXT,
    "additionalImage2" TEXT,
    "additionalImage3" TEXT,
    "additionalImage4" TEXT,
    "additionalImage5" TEXT,
    "brochure" TEXT,
    "warrantyCard" TEXT,
    "insuranceCertificate" TEXT,
    "invoice" TEXT,
    "others" TEXT,
    "agreed" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "WebsiteVariant_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "WebsiteVariant" ADD CONSTRAINT "WebsiteVariant_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WebsiteVariant" ADD CONSTRAINT "WebsiteVariant_brandId_fkey" FOREIGN KEY ("brandId") REFERENCES "Brand"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WebsiteVariant" ADD CONSTRAINT "WebsiteVariant_modelId_fkey" FOREIGN KEY ("modelId") REFERENCES "Model"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WebsiteVariant" ADD CONSTRAINT "WebsiteVariant_modelYearId_fkey" FOREIGN KEY ("modelYearId") REFERENCES "ModelYear"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WebsiteVariant" ADD CONSTRAINT "WebsiteVariant_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "Variant"("id") ON DELETE SET NULL ON UPDATE CASCADE;
